function Hd = Filter_Probe
%FILTER_PROBE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 14-May-2015 17:05:22

N     = 4;    % Order
F6dB1 = 0.4;  % First
F6dB2 = 0.6;  % Second

h = fdesign.bandpass('n,fc1,fc2', N, F6dB1, F6dB2, 'Linear');

Hd = design(h, 'window');

set(Hd, 'Arithmetic', 'single');

